using UnityEngine;

public class Coin : MonoBehaviour {
    private string _autoGeneratedID;
    private bool _isCollected;
    private Collider _collider;



    private void Awake() {
        _collider = GetComponent<Collider>();
        GeneratePersistentID();
    }

    private void GeneratePersistentID() {
        Vector3 pos = transform.position;
        _autoGeneratedID = $"{gameObject.scene.name}_Coin_{pos.x:F2}_{pos.y:F2}_{pos.z:F2}";
    }

    private void Start() {
        if (GameManager.Instance.IsCoinCollected(_autoGeneratedID)) {
            DisableCoinPermanently();
            return;
        }

        
        _isCollected = false;
        _collider.enabled = true;
        gameObject.SetActive(true);
    }

    private void OnTriggerEnter(Collider other) {
        if (!_isCollected && other.CompareTag("Player")) {
            _isCollected = true; 
            _collider.enabled = false; 

            GameManager.Instance.AddCoin(this);
            DisableCoinVisually();

       
          
            Debug.Log($"Collected coin: {_autoGeneratedID}");
        }
    }

    private void DisableCoinVisually() {
        gameObject.SetActive(false);
    }

    private void DisableCoinPermanently() {
        _collider.enabled = false;
        gameObject.SetActive(false);
        Destroy(gameObject);
    }

    public string GetCoinID() => _autoGeneratedID;
}